Améliorer le seo des pages actions
incubateur-ademe/nosgestesclimat-site pull request #1051
Opened 2023-05-15 13:10 UTC by dxb

fix #754 

- [x] Ajout d'une page plan du site
- [x] Ajout des pages actions dans le sitemap

<img width="758" alt="Capture d’écran 2023-05-15 à 15 28 41" src="https://github.com/datagir/nosgestesclimat-site/assets/67368/c7d1fae0-d256-42fb-89e5-f11f33853d59">

2023-05-30 12:49 UTC, bjlaa commented on source/components/Footer.tsx
> +						<Trans i18nKey="publicodes.planDuSite.title">plan du site</Trans>
```suggestion
						<Trans i18nKey="publicodes.planDuSite.title">Plan du site</Trans>
```

2023-05-30 12:52 UTC, bjlaa commented on source/locales/ui/ui-fr.yaml
> +  publicodes.planDuSite.title: Plan
```suggestion
  publicodes.planDuSite.title: Plan de site
```
Je pense que ce serait encore plus explicite d'écrire Plan de site partout :)

2023-05-30 12:53 UTC, bjlaa commented on source/sites/publicodes/pages/Plan.tsx
> +	Outils: {
Que penses-tu de "Nos outils" ici ?

2023-05-30 15:02 UTC, Clemog commented on source/sites/publicodes/pages/Plan.tsx
> +const actionsList = [
Pourtant elles sont dans la règles `actions` : https://github.com/datagir/nosgestesclimat/blob/master/data/actions.yaml

2023-05-31 13:59 UTC, laem commented on source/sites/publicodes/pages/Plan.tsx
> +const actionsList = [
Plutôt d'accord, à mon avis il faut les synchroniser. Une seule source de vérité.

2023-05-31 14:01 UTC, laem commented
@dxb pour moi cette PR ne corrige pas l'issue https://github.com/datagir/nosgestesclimat-site/issues/754#issuecomment-1557074675

N'hésite pas si mon commentaire n'est pas clair.

2023-05-31 14:01 UTC, laem requested changes
cf deux commentaires, l'un sur la récupération des actions, l'autre sur le sujet initial de cette PR

2023-05-31 16:46 UTC, laem commented
> A noter, que les actions sont également ajouter au sitemap dans cette PR.

Oui, mais le sitemap est à considérer comme significativement moins important que le fait d'avoir des liens découvrables. D'où le fait que l'issue concernait d'abord la découvrabilité des actions via le bouton action. 


>  De plus, les actions sont en dur dans le plan du site, pour éviter d'aller faire un fetch complémentaire et ainsi s'assurer que le html fourni au moteur de recherche soit le plus complet possible du premier coup.

OK je comprends l'idée mais ça me semble trop risqué d'avoir une désynchronisation des actions avec des liens morts, par rapport au gain d'un fetch qui prend quelque chose comme 100ms en plus.

2023-05-31 17:08 UTC, laem commented
J'ai fait un PR complémentaire pour avancer en parallèle sur ce sujet https://github.com/datagir/nosgestesclimat-site/pull/1087

2023-06-07 13:47 UTC, dxb commented on source/sites/publicodes/pages/Plan.tsx
> +const actionsList = [
C'est fait :)

2023-06-07 13:51 UTC, dxb commented
> Est-ce qu'on peut merger cette PR @dxb ? :)

J'ai fait la modif demandée, ajouter l'url du blog et les tests passent. Je dis Banco !

2023-06-07 14:22 UTC, bjlaa commented
Gogogo

2023-06-15 16:08 UTC, bjlaa commented
@laem tu as toujours des raisons de bloquer le merge de cette PR ?

2023-06-20 15:44 UTC, merged