Ajoute workflow Github pour veiller aux liens morts
incubateur-ademe/nosgestesclimat-site pull request #1271
Opened 2023-07-31 16:47 UTC by bjlaa

2023-08-01 15:43 UTC, EmileRolley requested changes
Trop bien :)

2023-08-01 15:43 UTC, EmileRolley commented on .github/workflows/check-links-validity.yaml
> +      - uses: ./.github/actions/install
bloquant: Je ne savais pas que l'on pouvait factoriser les workflows comme ça trop bien ! Il faudrait l'utiliser dans tout les autres workflow du coup :+1:

2023-08-01 15:43 UTC, EmileRolley commented on .github/workflows/check-links-validity.yaml
> +        uses: ./.github/actions/reopen-issue-with-comment
Autant je comprends la volonté de factoriser le yarn install, autant là je trouverait plus simple de tout avoir au même endroit perso. Ca évite de devoir switcher entre plusieurs fichiers : je souhaite savoir comme est faite la validation des liens j'ouvre le workflow avec le nom le plus parlant.

2023-08-02 13:53 UTC, bjlaa commented on .github/workflows/check-links-validity.yaml
> +      - uses: ./.github/actions/install
Yes ! Pourquoi est-ce que ça te parait bloquant ici ?

2023-08-02 13:56 UTC, bjlaa commented on .github/workflows/check-links-validity.yaml
> +        uses: ./.github/actions/reopen-issue-with-comment
Hmm ouais, j'ai vraiment repris leur implémentation en touchant quasi à rien. Je dois avouer que ça m'intéresse pas des masses de trifouiller des workflow Github / je suis pas ultra à l'aise avec. Si tu veux on peut créer une issue pour améliorer ce nouveau workflow à l'avenir, si ça botte quelqu'un de l'équipe

2023-08-02 14:46 UTC, EmileRolley commented on .github/workflows/check-links-validity.yaml
> +      - uses: ./.github/actions/install
Si on ne le fait pas maintenant on va l'oublier et on va se trimballer du code dupliqué.

2023-08-03 12:30 UTC, closed without merging