Fix mosaic features
incubateur-ademe/nosgestesclimat-site pull request #1301
Opened 2023-09-12 15:15 UTC by Clemog

Quelques fix pour https://github.com/incubateur-ademe/nosgestesclimat/pull/2060

- [ ] Ajout de la description pour les mosaïques
- [ ] Ordre des cartes pour des mosaïques de sélection qui ne sont pas des sommes
- [ ] Erreur TS

2023-09-13 09:16 UTC, EmileRolley requested changes
Je ne suis pas sûr de bien comprendre tous les tenants et aboutissants pour le tri des questions. Je t'ai fait quelques commentaires plus techniques sinon (de manière générale, si tu ressens le besoin de rajouter un commentaire pour expliquer ce que fait un ensemble d'instructions, il est généralement préférable de l'extraire dans une fonction :)

(A quel point cette logique sera utilisée dans la version Next @florianpanchout ?)

2023-09-13 09:16 UTC, EmileRolley commented on source/components/conversation/RuleInput.tsx
> +				return indexA - indexB
Donc là si je comprend bien, tu tris les question par rapport à leur parent direct. Pourquoi exactement ?

2023-09-13 09:16 UTC, EmileRolley commented on source/components/conversation/RuleInput.tsx
> +				const initialOrder = mosaicDottedNames.map(([dottedName, _]) =>
Tu as besoin de calculer qu'une seule fois `initialOrder` au début de ta fonction, pas besoin de mapper tous les noms à chaque comparaisons.

2023-09-13 09:16 UTC, EmileRolley commented on source/components/conversation/RuleInput.tsx
> +				if (indexA === -1) return 1 //some element of the sum can not being one of the card (ex: 'animaux domestiques')
Est-ce que tu peux détailler l'exemple ici, je ne suis pas sûr de comprendre là :thinking:

2023-09-13 09:16 UTC, EmileRolley commented on source/components/conversation/select/SelectDevices.tsx
> +									description={description}
:+1:

2023-09-13 13:32 UTC, EmileRolley commented
> > (A quel point cette logique sera utilisée dans la version Next @florianpanchout ?)
> 
> À 0%

Ok, ne te prends peut-être pas la tête avec mes remarques dans ce cas @Clemog :)

2023-09-14 09:39 UTC, Clemog commented on source/components/conversation/RuleInput.tsx
> +				return indexA - indexB
En essayant de résumé (ça rejoint le pb mentionné ici : https://github.com/incubateur-ademe/nosgestesclimat-site/issues/1093), l'ordre est aléatoire selon le navigateur. Je ne sais pas pourquoi mais le sort des cartes inactives réordonne d'une manière ou d'une autre les cartes 
Ici je tente de fixer l'ordre pour garantir l'ordre initial qui correspond à l'ordre d'apparition dans le code

2023-09-14 09:42 UTC, Clemog commented
Comment ça 0% ? 😂

2023-09-18 08:57 UTC, merged